name: PDF release
on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Install TinyTeX
      uses: r-lib/actions/setup-tinytex@v2
      env:
        TINYTEX_INSTALLER: TinyTeX

    - name: Install LaTeX packages
      run: |
        tlmgr install aurical auxhook bigintcalc bitset cjk etoolbox geometry gettitlestring hycolor hyperref infwarerr intcalc kvdefinekeys kvoptions kvsetkeys letltxmacro ltxcmds marginnote mathpazo microtype pdfescape pdftexcmds refcount titlesec url xcolor

    - name: Build PDFs
      run: |
        make cleanforce && make all
    
    # - name: Upload PDF artifact
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: pdf_file
    #     path: pdfs/book.pdf

    - name: Set variables
      id: vars
      run: |
        echo "::set-output name=date::$(date +'%Y-%m-%d')"
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    
    # - name: Download artifacts
    #   uses: actions/download-artifact@v2
    #   with:
    #     name: pdf_file

    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.vars.outputs.date }}-${{ steps.vars.outputs.sha8 }}
        name: ${{ steps.vars.outputs.date }} (commit ${{ steps.vars.outputs.sha8 }})
        draft: false
        prerelease: false
        files: |
          pdfs/book.pdf
          pdfs/ega0.pdf
          pdfs/ega1.pdf
          pdfs/ega2.pdf
          pdfs/ega3.pdf
          pdfs/ega4.pdf
